### PR TITLE
ALG4350-110: Update Readme

### PR DESCRIPTION
**Pull request by InfernalAmarok**
Summary of changes:
-Added guides for running BucStop locally and deploying it via AWS.
-Modified links in the Readme file to point to the new guides, along with the new Project Plan.
-Slightly modified wording in the Help section since we are no longer using Google Docs to link the guides.

### CODE REVIEW

**Review by waddelltw — CHANGES_REQUESTED** [review]
Can you put the deployment guide and the local instance guide in the Deployment directory inside of the Documentation folder on the repo? Other than that, it's fine.

**Comment by InfernalAmarok** [comment]
> Can you put the deployment guide and the local instance guide in the Deployment directory inside of the Documentation folder on the repo? Other than that, it's fine.

Change has been made.

**Review by waddelltw — APPROVED** [review]
LGTM :)

**Review by clafollette303 — APPROVED** [review]
LGTM

**Pull request merged**
